### PR TITLE
fix: `Navbar sticky updated`

### PR DESCRIPTION
**Pull request by Mucorp**
Freelancer project. Updated the navbar as discussed. Thanks

### CODE REVIEW

**Comment by glennlarsen** [comment]
Fade down/up animation as discussed. Also make sure that the code dont break any nav links from working.  For example when going to contact route scroll down and click on "reviews" link in the sticky NAV.

**Comment by Mucorp** [comment]
updated please check.

**Comment by glennlarsen** [comment]
Animation working as expected now. there are 2 issues.
issue1: /#howItWorks and /#reviews link dont scroll to section on home page as it should when using the sticky nav when coming from another route (like contact og get started).  
Test: Go to Contact or get Started page and scroll down, then click on howItWorks link,

issue2:  The initial mobile menu is not aligned correctly and has no hover effects. works for the sticky menu, but not when scroll is on top. 
Test: open any page in mobile screen size and open the burger menu without scrolling. then try to click the menu links.

**Comment by Mucorp** [comment]
Issue resolved, Please check

**Comment by glennlarsen** [comment]
Issue 1 routing is working. 

Issue 2 is still there. 
issue2: The Mobile menu when navigation state is onHide is not working correctly. It seems like the two mobile menu overlaps when the navigation is onHide. (when mobile menu is opened when scroll poisition is 0.
Test: open any page in mobile screen size and open the burger menu with scroll position 0(top). then try to click/hover the menu links. when doing one scroll the sticky mobile menu appears.

**Comment by Mucorp** [comment]
Updated

**Comment by glennlarsen** [comment]
perfect, everything working as expected

**Pull request closed without merging**
